services: 
  nginx_web_0:
    image: nginx
    networks:
      - nginx_network
  nginx_web_1:
    image: nginx
    networks:
      - nginx_network
  nginx_reverse_proxy:
    image: nginx
    networks:
      - nginx_network
    ports:
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d/

networks:
  nginx_network:
    driver: bridge